#!/bin/sh

echo "To trigger PiP, TAP and HOLD the video you are watching"
echo "To trigger PiP, TAP and HOLD the video you are watching"
echo "To trigger PiP, TAP and HOLD the video you are watching"
